server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/SpringCloud_Sell?characterEncoding=utf8&useSSL=false
  jpa:
    show-sql: true
      
env:
 dev3
 
girl:
  name: lili
  age: 301
