server:
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/SpringCloud_Sell?characterEncoding=utf8&useSSL=false
  rabbitmq:
    host: 111.231.202.87
    port: 5672
    username: guest
    password: guest
  jpa:
    show-sql: true

